# Generated by Django 3.1.7 on 2021-03-09 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210304_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'user'},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
